from collections import Counter
from pathlib import Path

from fastapi import HTTPException, status

DISCLAIMER = (
    "This report is generated by an AI-assisted triage system. "
    "It does not replace professional technical inspection. "
    "All findings require human review."
)


class ReportService:
    def __init__(self, reports_dir: Path | None = None) -> None:
        self.reports_dir = reports_dir or Path("storage") / "reports"

    def generate_report(self, inspection: dict, ordered_results: list[dict]) -> str:
        if not ordered_results:
            raise HTTPException(
                status_code=status.HTTP_409_CONFLICT,
                detail="Inspection has no processed results to generate a report.",
            )

        self.reports_dir.mkdir(parents=True, exist_ok=True)
        report_path = self.reports_dir / f"{inspection['inspection_id']}.md"
        report_content = self._build_markdown(inspection, ordered_results)
        report_path.write_text(report_content, encoding="utf-8")

        return f"/storage/reports/{inspection['inspection_id']}.md"

    def _build_markdown(self, inspection: dict, ordered_results: list[dict]) -> str:
        severity_counts = Counter(result["severity"] for result in ordered_results)

        lines: list[str] = [
            "# SolarInspect AI Report",
            "",
            f"- Inspection ID: `{inspection['inspection_id']}`",
            f"- Plant Name: `{inspection['plant_name']}`",
            f"- Inspection Type: `{inspection['inspection_type']}`",
            f"- Status: `{inspection['status']}`",
            f"- Total Images: `{inspection['total_images']}`",
            "",
            "## Findings by Severity",
            "",
        ]

        for severity in ("critical", "high", "medium", "low", "healthy", "unknown"):
            lines.append(f"- {severity}: `{severity_counts.get(severity, 0)}`")

        lines.extend(
            [
                "",
                "## Findings (Ordered by Priority)",
                "",
            ]
        )

        for result in ordered_results:
            lines.extend(
                [
                    f"### {result['filename']}",
                    f"- Priority: `{result['priority']}`",
                    f"- Raw Label: `{result['raw_label']}`",
                    f"- Category: `{result['category']}`",
                    f"- Severity: `{result['severity']}`",
                    f"- Confidence: `{result['confidence']}`",
                    f"- Evidence: {result['evidence']}",
                    f"- Explanation: {result['explanation']}",
                    f"- Recommended Action: {result['recommended_action']}",
                    "",
                ]
            )

        lines.extend(
            [
                "## Disclaimer",
                "",
                DISCLAIMER,
                "",
            ]
        )

        return "\n".join(lines)


report_service = ReportService()
